# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

["Workholding & Indexing", "Machine Tools", "Precision Measuring Tools", "Machine Tool Accessories", "Spindle Tooling", "Cutting Tools", "Coolants", "Tool Storage"].each_with_index do |name, i|
  Category.create(:name => name, :position => i)
end


category1 = Category.find_by_name("Workholding & Indexing")
category2 = Category.find_by_name("Machine Tools")
category3 = Category.find_by_name("Precision Measuring Tools")
category4 = Category.find_by_name("Machine Tool Accessories")
category5 = Category.find_by_name("Spindle Tooling")
category6 = Category.find_by_name("Cutting Tools")
category7 = Category.find_by_name("Coolants")
category8 = Category.find_by_name("Tool Storage")


Product.create(:category => category5, :name => 'V-Flange, Collets and Custom Tools', :premier => true, :position => 3, :company => 'Lyndex Nikken')
Product.create(:category => category1, :name => 'Quick Change Collet Chucks, Precision Air Chucks', :premier => false, :position => 5, :company => 'MicroCentric')
Product.create(:category => category1, :name => 'Used, New', :premier => true, :position => 8, :company => 'HTS')
Product.create(:category => category1, :name => 'High Precision Air Chucks', :premier => false, :position => 7, :company => 'Northfield')
Product.create(:category => category1, :name => 'Power Chucks and Cylinders', :premier => false, :position => 8, :company => 'SP')
Product.create(:category => category1, :name => 'Power Chucks, Cylinders, Steady Rests', :premier => true, :position => 5, :company => 'SMW Autoblok')
Product.create(:category => category1, :name => 'Manual and Power Chucks', :premier => false, :position => 2, :company => 'Buck Chucks')
Product.create(:category => category1, :name => 'Power Chucks and Cylinders', :premier => false, :position => 11, :company => 'Kitagawa')
Product.create(:category => category1, :name => 'Power Chucks and Cylinders', :premier => false, :position => 12, :company => 'Matsumoto')
Product.create(:category => category1, :name => 'Chucks, Pallet Changers, Bar Feeds', :premier => false, :position => 13, :company => 'SMW')
Product.create(:category => category1, :name => 'Manual and Automatic Steady Rests', :premier => false, :position => 14, :company => 'Steady Rests')
Product.create(:category => category1, :name => 'Pallet Systems', :premier => false, :position => 15, :company => 'Midaco')
Product.create(:category => category1, :name => 'Top Jaws, Chucks, Cylinders', :premier => false, :position => 16, :company => 'Huron')
Product.create(:category => category1, :name => 'Chucks and Cylinders', :premier => false, :position => 17, :company => 'Howa')
Product.create(:category => category1, :name => 'Hard and Soft Jaws', :premier => false, :position => 18, :company => 'Dillon')
Product.create(:category => category1, :name => 'Pie Jaws and Tooling Columns', :premier => false, :position => 1, :company => 'Abbott')
Product.create(:category => category1, :name => 'Hard and Soft Jaws', :premier => false, :position => 20, :company => 'Daco')
Product.create(:category => category1, :name => 'Clamp Systems', :premier => false, :position => 21, :company => 'Mitee Bite')
Product.create(:category => category1, :name => 'Collets and Tooling', :premier => false, :position => 22, :company => 'Somma Balas')
Product.create(:category => category1, :name => 'Collet Chucks', :premier => false, :position => 0, :company => 'ATS')
Product.create(:category => category1, :name => 'Anglock and DoubleLock Vises', :premier => false, :position => 24, :company => 'Kurt')
Product.create(:category => category1, :name => 'Original 2 Station Vises', :premier => true, :position => 2, :company => 'Chick')
Product.create(:category => category1, :name => 'Rotary Tables', :premier => false, :position => 26, :company => 'Troyke')
Product.create(:category => category1, :name => 'Magnetic Chucks', :premier => false, :position => 27, :company => 'O.S. Walker')
Product.create(:category => category1, :name => 'Bar Feed Systems', :premier => false, :position => 28, :company => 'LNS America')
Product.create(:category => category1, :name => 'Custom Machining Center Fixtures', :premier => false, :position => 29, :company => 'WMCF')
Product.create(:category => category1, :name => 'Special ID and OD Collet Chucks', :premier => false, :position => 30, :company => 'HXT Systems')
Product.create(:category => category1, :name => 'Tombstones', :premier => false, :position => 32, :company => 'Midstate Machine')
Product.create(:category => category2, :name => 'CNC Mills and Lathes', :premier => false, :position => 33, :company => 'Fryer Machines')
Product.create(:category => category2, :name => 'Milling Machines', :premier => false, :position => 34, :company => 'Alliant')
Product.create(:category => category2, :name => 'Precision Lathes', :premier => false, :position => 35, :company => 'Harrison')
Product.create(:category => category2, :name => 'Bandsaws, Ironworkers', :premier => false, :position => 36, :company => 'Marvel')
Product.create(:category => category2, :name => 'Machine Tools', :premier => false, :position => 37, :company => 'Clausing')
Product.create(:category => category2, :name => 'Machine Tools', :premier => false, :position => 38, :company => 'Sharp Industries')
Product.create(:category => category2, :name => 'Wire and Sink EDM\'s', :premier => false, :position => 39, :company => 'Sodick')
Product.create(:category => category2, :name => 'Drill and Tool Grinders', :premier => true, :position => 4, :company => 'Rush Machinery')
Product.create(:category => category2, :name => 'Precision Lathes', :premier => false, :position => 41, :company => 'Nardini')
Product.create(:category => category2, :name => 'Lathes, Mills, Grinders', :premier => false, :position => 42, :company => 'Acer')
Product.create(:category => category2, :name => 'Machine Tools', :premier => false, :position => 43, :company => 'Willis')
Product.create(:category => category2, :name => 'Contour Grinders', :premier => false, :position => 44, :company => 'Wasino')
Product.create(:category => category2, :name => 'Presses and Cutoff Saws', :premier => false, :position => 45, :company => 'Dake')
Product.create(:category => category2, :name => 'Machine Tools', :premier => false, :position => 46, :company => 'Summit')
Product.create(:category => category5, :name => 'Live Tools', :premier => false, :position => 47, :company => 'Bristol Tools')
Product.create(:category => category5, :name => 'Keyless Drill Chucks', :premier => false, :position => 48, :company => 'Albrecht')
Product.create(:category => category5, :name => 'Drill chucks', :premier => false, :position => 49, :company => 'Jacobs')
Product.create(:category => category5, :name => 'V Flange, Drill and Tap Holders', :premier => false, :position => 50, :company => 'Collis')
Product.create(:category => category2, :name => 'Coordinate Measuring Machines', :premier => true, :position => 6, :company => 'Brown and Sharpe')
Product.create(:category => category5, :name => 'V-Flange Tooling', :premier => false, :position => 52, :company => 'Command')
Product.create(:category => category5, :name => 'V Flange Tooling', :premier => false, :position => 54, :company => 'Tecnara')
Product.create(:category => category5, :name => 'CNProduct.create(:category => category5,nd VDI Tooling', :premier => false, :position => 55, :company => 'Techleader')
Product.create(:category => category1, :name => 'Tsudakoma Rotary Tables', :premier => false, :position => 56, :company => 'Koma Precision')
Product.create(:category => category4, :name => 'Machine Tool Accessories', :premier => false, :position => 57, :company => 'Royal')
Product.create(:category => category1, :name => 'Rotary Tables and Indexers', :premier => false, :position => 58, :company => 'Haas')
Product.create(:category => category4, :name => 'Tool Presetters', :premier => false, :position => 59, :company => 'Lyndex')
Product.create(:category => category4, :name => 'Digital Readout Systems', :premier => false, :position => 60, :company => 'Mititoyo')
Product.create(:category => category4, :name => 'Digital Readout Systems', :premier => false, :position => 61, :company => 'Acu-Rite')
Product.create(:category => category4, :name => 'VDI Tooling, Bushings, Sleeves', :premier => false, :position => 62, :company => 'CNC')
Product.create(:category => category4, :name => 'Power Feeds', :premier => false, :position => 63, :company => 'Servo')
Product.create(:category => category4, :name => 'Chip Conveyor Systems', :premier => false, :position => 64, :company => 'Mayfran')
Product.create(:category => category4, :name => 'Chip Conveyor Systems', :premier => false, :position => 65, :company => 'Turbo')
Product.create(:category => category1, :name => 'Chip Conveyor Systems', :premier => false, :position => 66, :company => 'Jorgenson')
Product.create(:category => category4, :name => 'Boring Heads', :premier => false, :position => 67, :company => 'Criterion')
Product.create(:category => category1, :name => 'Modular Fixturing', :premier => false, :position => 68, :company => 'Stevens')
Product.create(:category => category4, :name => 'Quick Change Tool Posts', :premier => false, :position => 69, :company => 'Aloris')
Product.create(:category => category4, :name => 'Grinding Wheel Adapters', :premier => false, :position => 70, :company => 'Sopko')
Product.create(:category => category4, :name => 'Static and Live Tooling', :premier => false, :position => 71, :company => 'VDI')
Product.create(:category => category1, :name => 'Live and Dead Centers', :premier => false, :position => 72, :company => 'Riten')
Product.create(:category => category6, :name => 'Carbide, Cermets, Ceramics', :premier => true, :position => 0, :company => 'Kyocera and Ceratip')
Product.create(:category => category6, :name => 'Indexable Threading and Thread Milling', :premier => false, :position => 74, :company => 'Duramet')
Product.create(:category => category6, :name => 'Special Taps and Gages', :premier => false, :position => 75, :company => 'N. American')
Product.create(:category => category6, :name => 'HSS and Carbide Coolant Fed Reamers', :premier => false, :position => 76, :company => 'Metcut/Barber Coleman')
Product.create(:category => category6, :name => 'End Cutting Tools, Counterbores, Countersinks', :premier => false, :position => 77, :company => 'Metcut/Eclipse')
Product.create(:category => category6, :name => 'Indexable Carbide Milling Roughers', :premier => false, :position => 78, :company => 'Triphase')
Product.create(:category => category6, :name => 'Indexable Carbide Grooving', :premier => false, :position => 79, :company => 'Allied Tool')
Product.create(:category => category6, :name => 'Indexable Threading and Thread Milling', :premier => false, :position => 80, :company => 'Vardex')
Product.create(:category => category2, :name => 'Bandsaws', :premier => false, :position => 81, :company => 'Cosan')
Product.create(:category => category3, :name => 'Precision Measuring Tools', :premier => false, :position => 82, :company => 'Brown and Sharpe')
Product.create(:category => category3, :name => 'Precision Measuring Tools', :premier => false, :position => 83, :company => 'Starrett')
Product.create(:category => category3, :name => 'Precision Measuring Tools', :premier => false, :position => 84, :company => 'Fowler')
Product.create(:category => category3, :name => 'Precision Measuring Tools', :premier => false, :position => 85, :company => 'Flexbar')
Product.create(:category => category8, :name => 'Modular Tool Cabinets', :premier => false, :position => 86, :company => 'Stor-Loc')
Product.create(:category => category8, :name => 'Tool Boxes and Cabinets', :premier => false, :position => 87, :company => 'Kennedy')
Product.create(:category => category8, :name => 'V-Flange Tool Carts', :premier => false, :position => 88, :company => 'Vertikart')
Product.create(:category => category2, :name => 'Vertical Milling Machines', :premier => true, :position => 7, :company => 'Bridgeport Machine Tools')
Product.create(:category => category8, :name => 'Tool Cabinets', :premier => true, :position => 9, :company => 'Lista Corporation')
Product.create(:category => category7, :name => 'Coolants, Machining Oils, Cleaners, Equipment', :premier => true, :position => 1, :company => 'Master Chemical')
Product.create(:category => category4, :name => 'High Speed Spindles', :premier => true, :position => 0, :company => 'NSK America')



NewsItem.create(:description => 'We are now offering Bridgeport Machine Tools and Lista Cabinets.', :dateString => "3/21/2008")
NewsItem.create(:description => 'Herr Tool Sales is proud to announce the addition of the Master Chemical top quality line of coolants, cutting oils, machine cleaners and equipment.', :dateString => "4/19/2004")
NewsItem.create(:description => 'NSK America is continuing to expand their product line of precision high speed spindles.', :dateString => "3/22/2009")

User.create(:email => 'jtherr@gmail.com', :password => "o0plki9o", :password_confirmation => "o0plki9o")
User.create(:email => 'tom@herrtoolsales.com', :password => "hallam", :password_confirmation => "hallam")
